name: rikulo_highcharts_example_app
description: A web app example for rikulo_highcharts.

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  rikulo_highcharts:
    path: ../

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
