name: rikulo_highcharts
version: 3.0.0
description: Highcharts is a wrapper of highcharts in Dart.
homepage: https://github.com/rikulo/highcharts
documentation: https://pub.dev/documentation/rikulo_highcharts/latest/
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  js: any
